### PR TITLE
#17 taskname:Deleting a product from vendor's collection by his/here own

### PR DESCRIPTION
**Pull request by BenoitIT**
#### What does this PR do?

--- this PR is there to highlight implementation of the following subtasks:
* create delete product endpoint in productRoutes file
* create deleteProduct function in productController
* under the deleteProduct function these statements below was accomplished.
* get a single  product with its related images and different variations using product id from params
*  make sure that the product was registered by the loggin vendor
*  if the product registered by loggin in vendor lost ..appropriate error message is being given
* once the products found and its corresponding related model .function to delete it get called
*  once delete is successfull appropriate message get returned to the user

#### Description of Task to be completed?

 * login app under this endpoint `http://localhost:{PORT}/api/admin/login` with registered vendor credentials
* otherwise you will not be allowed
*  make sure that you have the products in collections
*  from added products grab one product's id and pass it after the following endpoint and do as it looks with added product id
* Hint the following end point
`DELETE  /api/v1/products/delete/:d `

#### How should this be manually tested?

* clone the repository using this link https://github.com/atlp-rwanda/ecommerce-app-legends-bn 
* once the files from the repo get opened in appropriate text editor
* switch to `ft-delete-product` branch
*  run `npm i` to install updated dependencies
*  run `npm run dev` to start the server
*  use postman or documentation found on this link `http://localhost:{PORT}/docs/`
*  run this route `'http://localhost:4000/api/v1/products/delete/:id`

#### Any background context you want to provide?

implementation delete product functionality and handling vendor successfull authenticated token provision
the images are being deleted directly from cloud as well

#### What are the relevant Trello stories?
trello stroy number 17

#### Questions:
review and give some feedbacks

### CODE REVIEW

**Review by Evaristekanova — CHANGES_REQUESTED** [review]
@BenoitIT  try to resolve the conflicts

**Review by Evaristekanova — APPROVED** [review]
it works perfect.

**Review by Christabll — APPROVED** [review]

**Review by FabCode67 — APPROVED** [review]

**Review by Aimeana100 — APPROVED** [review]
well

**Review by mansurissa — APPROVED** [review]

**Comment by Aimeana100** [comment]
[A seller should be able to delete a specific item from their collection](https://trello.com/c/2WxOvH1i/59-a-seller-should-be-able-to-delete-a-specific-item-from-their-collection)

**Pull request merged**
