### PR TITLE
#chore[Multiple Language Setup]

### PR DESCRIPTION
**Pull request by ngoma3**
## this is a chore branch for setting up multiple languages  using i18next ## material(packages) used are :

- `i18next` for setting language resources and translation .
- `i18next-fs-backend` for loading the file system path for the translation files.
- `i18next-http-middleware` for handling request language in headers

## what I did:

- I have installed all packegs, some of them are mentioned above.
- I have created locales folder within root folder which contains translation files for english and french.
- I have configured i18next in index.js and setup app to use i18next middleware

## how to run:

- git clone from repo
- `run git checkout ch-multiple-languages-setup`
- `run npm i`.
- configure and create and configure database .
- `run npm dev`.
- use postman to test and specify `Accept-language` as key in headers with value of `en` or `fr`.

## Clarified example

i18next

### CODE REVIEW

**Review by BenoitIT — APPROVED** [review]
good work,code runs smoothly

**Comment by Evaristekanova** [comment]
I tested @ngoma3's PR, it is working pretty as expected

**Review by Evaristekanova — APPROVED** [review]

**Review by FabCode67 — APPROVED** [review]
good job @ngoma3

**Review by mansurissa — APPROVED** [review]
Great!

**Pull request merged**
