### PR TITLE
 #130612935 setup roles and permissions

### PR DESCRIPTION
**Pull request by Kevin-ishimwe**
#### What does this PR do?
adds roles and permissions to users in the backend database

#### Description of Task to be completed?
-  setup of users,role,permissions,rolepermission table
- making associations for the table
- endpoint for adding users with relevant roles(admin) 
- fixing tests setup to synchronize the database
- adding tests for admin endpoints 
- README update
`POST /api/admin/users`
- endpoint for getting all users
`GET /api/admin/users`
- endpoint for deleting any user
`DELETE /api/admin/users/id`

#### How should this be manually tested?
`npx sequelize-cli db:migrate --name 20230307173657-create-role.js`
`npm run migrate`
`npm run dev`
use post man to interact with and test the apis

#### What are the relevant pivotal tracker/Trello stories?
Create Roles and Set Permissions #

### CODE REVIEW

**Review by Aimeana100 — DISMISSED** [review]
You did great Job @Kevin-ishimwe , but  you may improve by  Configuring the hound to follow esLint as codes analyser, and 
since the system is wide let change something in file structure,
like: 
```controller/Admin/*.js```
```controller/Vendor/```
```controller/Buyer/```
or 
```controller/Admin/*.js```
```controller/User/``` : User being other users apart from admin

**Comment by BenoitIT** [comment]
good job but remember to work on response translation

**Review by FabCode67 — COMMENTED** [review]
@Kevin-ishimwe  what about tests, swagger and translations

**Comment by Kevin-ishimwe** [comment]
> @Kevin-ishimwe what about tests, swagger and translations

done

**Comment by Kevin-ishimwe** [comment]
> 

done

**Review by Evaristekanova — APPROVED** [review]

**Review by FabCode67 — APPROVED** [review]

**Review by BenoitIT — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]
LGTM

**Pull request merged**
