### PR TITLE
Ft user update profile

### PR DESCRIPTION
**Pull request by Christabll**
Updating User Profile Branch:

This branch includes several updates to the user profile functionality. The updates are as follows:

1. User Registration: Users can now register themselves on the platform. When they register, they will be provided with a token containing their information.

2. Token-Based Authentication: To update their profile, users only need to pass the token in the headers of their request. This improves security by reducing the risk of sensitive information being exposed in the request body.

3. Profile Update: The profile update functionality has been improved to allow users to update their information, such as their name, email, or profile picture.

4. Error Handling: Improved error handling has been implemented to provide users with more helpful error messages if they encounter any issues during the registration or update process.

Overall, these updates improve the user experience by streamlining the profile update process and making it more secure. Users can now register themselves, update their information easily, and do so securely by using tokens in the headers of their requests.```

### CODE REVIEW

**Review by Evaristekanova — CHANGES_REQUESTED** [review]
@Christa22 you have conflicts try to resolve them and squash other commits we we need to see 1 commit on your PR

**Review by Evaristekanova — APPROVED** [review]
it works perfectly

**Review by FabCode67 — APPROVED** [review]
done

**Review by BenoitIT — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]

**Comment by Aimeana100** [comment]
@Christa22 ,  you may  Modify the PR message so that we can easly get guided on how to test!! 🤲🏽

**Pull request merged**
