### PR TITLE
#18  feature view single product by a buyer

### PR DESCRIPTION
**Pull request by Evaristekanova**
### what this PR do?

- view single product by a buyer

### description of task to completed
- have this endpoint working GET "/api/v1/buyers/:id" 

### how should this be manually tested

- clone this repo
- switch in ft-buyer-view-single-product-14
- open terminal
- run "npm i" to install all dependencies
- run "npm run dev" to start server
- open postman and use the above route 
- open documentation with this link "localhost:{{port}}/docs"

### trello story number 
- number  18

### screenshot

Screenshot 2023-03-24 112130

### questions
- review this and provide feedback

### CODE REVIEW

**Review by Aimeana100 — COMMENTED** [review]
Great @Evaristekanova, you did but you better have to return both product Images and attributes  as the product property.

**Review by FabCode67 — COMMENTED** [review]
done

**Review by FabCode67 — APPROVED** [review]

**Review by BenoitIT — APPROVED** [review]

**Review by Aimeana100 — APPROVED** [review]
well done

**Review by mansurissa — APPROVED** [review]
LGTM

**Pull request merged**
