### PR TITLE
feat[ft-password-reset]

### PR DESCRIPTION
**Pull request by ngoma3**
**I have added some features where a person who is already logged in can reset the password by passing the old password without having to send the email and also the token for resetting password can only be used once.**

 This branch will allow a user to reset his/her account password by sending a link via the user's email

- allow user to reset password
- write its swagger documentation
- this branch contains middle ware file for setting authentications to user
#### How to run
- git clone from repo
- git checkout ft-password-rese
- set .env as shown in .envexample
- run npm i
- run npm run dev
- copy this url in your postman: http://localhost:{port}/api/v1/email,
- chose your email and test it
- after the email verification you may receive a mail message with the token
- use this link http://localhost:{port}/api/v1/password with a specified token in headers
- set your password.

feat[WIP ft-password-reset]

feat[ft-password-reset]

### CODE REVIEW

**Review by FabCode67 — APPROVED** [review]
double check on your tests @ngoma3

**Review by FabCode67 — COMMENTED** [review]
double check on tests

**Review by Evaristekanova — CHANGES_REQUESTED** [review]
your tests are failing try to fix them

**Review by FabCode67 — APPROVED** [review]

**Review by Evaristekanova — APPROVED** [review]

**Review by BenoitIT — APPROVED** [review]

**Review by mansurissa — APPROVED** [review]
Check as a whole team if you are using the same code formatter for this project because this PR had many changed files because of spaces and trailing commas.

**Pull request merged**
