### PR TITLE
houndci configuration

### PR DESCRIPTION
**Pull request by Evaristekanova**
##  description of the task

- add hound config file
- this file will be used to configure houndci-bot
- houndci-bot will be used to check for style violations in the codebase
- this will be done automatically when a pull request is created
- houndci-bot will comment on the pull request with the style violations
- the developer will then fix the style violations and push the changes
- houndci-bot will then check the pull request again and comment on the pull request
- these configuration in this file will let houndci bot work with eslint

ch[setup-github-actions]

### CODE REVIEW

**Review by Aimeana100 — APPROVED** [review]
Well, this should be absolutely what we has looking for! 👍

**Review by Aimeana100 — CHANGES_REQUESTED** [review]
@Evaristekanova  , You have done it well. but due to the current PR merge, you may resolve the conflicts that araised.

**Review by BenoitIT — APPROVED** [review]

**Review by FabCode67 — APPROVED** [review]
Great!

**Review by Aimeana100 — APPROVED** [review]
great!! however you have more than commits [⚠️](https://emojipedia.org/emoji/%E2%9A%A0%EF%B8%8F/)

**Review by mansurissa — APPROVED** [review]

**Pull request merged**
