### PR TITLE
GitHub Actions and Pipeline setup

### PR DESCRIPTION
**Pull request by Evaristekanova**
## This commit adds a GitHub actions setup for the project.

- this repo contains a .yml file that will be used to setup
- contains secrets which will be used to run the project
- contains a command to run the testing
- contains a command to install all dependencies for the project
- contains a command to build if it exists

ch[github actions setup]

### CODE REVIEW

**Review by FabCode67 — APPROVED** [review]
good job @Evaristekanova  , codes are formatted well , I think it fails because the `test` script doesn't have any test to run. I think if it merged with tests chore , git actions will run successfully .

**Review by BenoitIT — APPROVED** [review]
everything works but get failed when it comes to test script ..hopefully once test chore merged this is gonna get successful

**Review by Aimeana100 — APPROVED** [review]
Cong's well done.

**Review by mansurissa — APPROVED** [review]
Looks good!

**Pull request merged**
